name: Build demo

#on:
#  push:
#    branches: [ master ]

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: self-hosted
    steps:
      - name: demo build
        run: |
          rm -rf InkWatchy-demo 1>/dev/null 2>/dev/null

          git config --global http.version HTTP/1.1
          git config --global core.compression 0

          git clone https://github.com/Szybet/InkWatchy.git InkWatchy-demo
          cd InkWatchy-demo

          COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          if [[ $COMMIT_MESSAGE == *":clean-pio" ]]; then
            echo "Cleaning pio packages, as requested"
            rm -rf ~/.platformio/packages/framework-arduinoespressif32/
            rm -rf ~/.platformio/packages/framework-espidf/
            rm -rf ~/.platformio/platforms/*
          else
            echo "Not cleaning platformio packages"
          fi

          ./resources/tools/other/compile/demoMaker.sh
          cd ..
      - name: Upload demo program
        uses: actions/upload-artifact@v4
        with:
          name: demo-program
          path: InkWatchy-demo/resources/tools/other/out/demo-program.bin
      - name: Upload demo source
        uses: actions/upload-artifact@v4
        with:
          name: demo-source
          path: InkWatchy-demo/resources/tools/other/out/demo-source.zip
