// The editor's side of "what timezone is this watch in".
//
// The device cannot be told "Europe/Paris" -- there is no tzdata on it to look
// that up in. What its libc understands is a POSIX TZ string:
//
//     CET-1CEST,M3.5.0,M10.5.0/3
//     └┬─┘ │└─┬┘│      └───┬───┘
//      │   │  │  │          └ DST ends: month 10, last (5th) Sunday (0), 03:00
//      │   │  │  └ DST begins: month 3, last Sunday, 02:00 (POSIX's default)
//      │   │  └ abbreviation while DST is in force
//      │   └ hours to ADD TO LOCAL TIME TO GET UTC -- so UTC+1 is spelled "-1"
//      └ abbreviation while standard time is in force
//
// i.e. the standard offset plus the two dates on which it changes. Sending the
// RULES rather than a single offset is what lets the watch be right in both
// halves of the year: see M5Paper_MicroPatterns/src/mp_clock.h for why daylight
// saving can only ever be applied at an NTP sync on these devices.
//
// So this module's whole job is IANA name -> POSIX string, and it does that with
// a lookup, not a computation. Every zone's POSIX string is published by IANA in
// the footer of its compiled TZif file, and posix_tz.js is those footers,
// generated by tools/gen_posix_tz.py. That script's header explains at length
// why deriving the string from browser Intl data instead -- which is what this
// file used to do -- produced strings that were confidently wrong for zones like
// America/Vancouver and Africa/Casablanca.
//
// Intl is still used here, but only for DISPLAY: the current offset and clock
// reading shown next to the picker, so the user can sanity-check the zone they
// chose. Nothing sent to the device comes from it.

import { POSIX_TZ, TZDATA_VERSION } from './posix_tz.js';

export { TZDATA_VERSION };

/** The browser's own IANA zone name, or '' if it will not say. */
export function detectTimeZoneName() {
    try {
        return Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    } catch (e) {
        return '';
    }
}

/** Every zone we have a POSIX string for, sorted. This is the picker's list. */
export function listTimeZoneNames() {
    return Object.keys(POSIX_TZ).sort();
}

/** The POSIX TZ string for a zone, or null if the table does not have it. */
export function lookupPosixTZ(zone) {
    return Object.prototype.hasOwnProperty.call(POSIX_TZ, zone) ? POSIX_TZ[zone] : null;
}

/** Human-readable "UTC+05:30" for an offset in minutes east of UTC. */
export function formatOffset(minutesEast) {
    const sign = minutesEast < 0 ? '-' : '+';
    const abs = Math.abs(minutesEast);
    return `UTC${sign}${String(Math.floor(abs / 60)).padStart(2, '0')}:${String(abs % 60).padStart(2, '0')}`;
}

/**
 * Minutes east of UTC in `zone` right now, for display only.
 *
 * Formats the instant into the zone's wall clock and reads that clock back as
 * if it were UTC; the difference is the offset. Returns null for a zone this
 * browser does not know, which is not the same question as whether our table
 * knows it -- the two can be on different tzdata versions.
 */
export function currentOffsetMinutes(zone, now = new Date()) {
    try {
        const parts = {};
        const fmt = new Intl.DateTimeFormat('en-US', {
            timeZone: zone,
            // hourCycle h23, not hour12:false: the latter can render midnight
            // as "24" in some locales, which then reads as the following day.
            hourCycle: 'h23',
            year: 'numeric', month: '2-digit', day: '2-digit',
            hour: '2-digit', minute: '2-digit', second: '2-digit'
        });
        for (const part of fmt.formatToParts(now)) {
            if (part.type !== 'literal') parts[part.type] = parseInt(part.value, 10);
        }
        const asIfUTC = Date.UTC(parts.year, parts.month - 1, parts.day,
            parts.hour, parts.minute, parts.second);
        return Math.round((asIfUTC - Math.floor(now.getTime() / 1000) * 1000) / 60000);
    } catch (e) {
        return null;
    }
}

/** The wall-clock reading in `zone` right now ("14:07"), or '' if unknown. */
export function currentTimeIn(zone, now = new Date()) {
    try {
        return new Intl.DateTimeFormat('en-GB', {
            timeZone: zone, hourCycle: 'h23', hour: '2-digit', minute: '2-digit'
        }).format(now);
    } catch (e) {
        return '';
    }
}

/**
 * The offsets a POSIX TZ string states, in minutes east of UTC.
 *
 * Deliberately NOT a rule engine -- it reads the two numeric offset fields and
 * ignores the switch dates entirely. That is enough for the one question the
 * panel asks: is the zone currently on one of the offsets this string can
 * produce? Africa/Casablanca is why. IANA publishes "<+00>0" for it and gives
 * up on the Ramadan rule, so the string says UTC+0 while the zone is really on
 * UTC+1 for most of the year, and a watch sent that string would read an hour
 * early with nothing to say why. Comparing against the browser's live offset
 * turns that into something the panel can warn about.
 *
 * Remember the POSIX sign convention: the field is the amount to ADD TO LOCAL
 * TIME TO REACH UTC, so "CET-1" is UTC+1 and the sign flips on the way in.
 *
 * @returns {{std: number, dst: number|null}|null} null if it will not parse.
 */
export function posixOffsets(tz) {
    const NAME = '(?:<[-+0-9A-Za-z]{1,11}>|[A-Za-z]{3,11})';
    const OFFSET = '([-+]?\\d{1,2}(?::\\d{1,2}){0,2})';
    const match = new RegExp(`^${NAME}${OFFSET}(?:(${NAME})${OFFSET}?)?(?:,.*)?$`).exec(tz || '');
    if (!match) return null;

    const toMinutes = (field) => {
        const sign = field.startsWith('-') ? -1 : 1;
        const [h, m = '0', s = '0'] = field.replace(/^[-+]/, '').split(':');
        const magnitude = parseInt(h, 10) * 60 + parseInt(m, 10) + Math.round(parseInt(s, 10) / 60);
        return -sign * magnitude;          // POSIX sign is inverted
    };

    const std = toMinutes(match[1]);
    // A daylight name with no offset after it means "one hour ahead of
    // standard", which is POSIX's default and how tzdata writes most zones
    // (EST5EDT, AEST-10AEDT).
    const dst = match[2] === undefined ? null : (match[3] === undefined ? std + 60 : toMinutes(match[3]));
    return { std, dst };
}

/**
 * Everything the setup panel needs to know about a zone.
 *
 * @param {string} zone  IANA name, e.g. "Europe/Paris"
 * @returns {{
 *   zone: string,
 *   tz: string|null,          // POSIX string to send, null if we have none
 *   known: boolean,           // false = not in our table, cannot be sent
 *   hasDstRule: boolean,      // does the string carry a daylight-saving switch
 *   offsetMinutes: number|null,
 *   localTime: string,
 *   offsetAgrees: boolean|null,   // can the rule produce the zone's live offset
 *   ruleOffsets: {std, dst}|null
 * }}
 */
export function describeTimeZone(zone, now = new Date()) {
    const tz = lookupPosixTZ(zone);
    const rule = tz === null ? null : posixOffsets(tz);
    const live = currentOffsetMinutes(zone, now);
    return {
        zone,
        tz,
        known: tz !== null,
        // A comma is what separates the offsets from the switch dates, so its
        // presence is exactly "this rule has a daylight-saving period". A zone
        // without one is either genuinely fixed (Asia/Kolkata) or one whose
        // rules IANA declines to express in POSIX at all (Africa/Casablanca,
        // whose Ramadan shift needs a second DST period POSIX has no room for).
        hasDstRule: tz !== null && tz.indexOf(',') !== -1,
        offsetMinutes: live,
        localTime: currentTimeIn(zone, now),
        ruleOffsets: rule,
        // null when we cannot compare -- no rule, or a browser that does not
        // know the zone. Otherwise: does the rule have an offset matching the
        // one the zone is actually on right now?
        offsetAgrees: (rule === null || live === null)
            ? null
            : (live === rule.std || live === rule.dst)
    };
}
